call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'

Plug 'tpope/vim-fugitive'
" Plug 'git://git.wincent.com/command-t.git'
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline'

Plug 'scrooloose/nerdtree'
" Plug 'valloric/youcompleteme'

Plug 'airblade/vim-gitgutter'
Plug 'scrooloose/syntastic'

Plug 'majutsushi/tagbar'

Plug 'asciidoc/vim-asciidoc'
Plug 'jceb/vim-orgmode'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
Plug 'chriskempson/base16-vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'francoiscabrol/ranger.vim'
Plug 'rbgrouleff/bclose.vim'
" List ends here. Plugins become visible to Vim after this call.
call plug#end()
if $TERM == 'cygwin'
		colorscheme base16-default-dark
else
		colorscheme onedark
endif
set clipboard=unnamed " use OS clipboard

let g:ctrlp_working_path_mode = 'ra'
nmap <F8> :TagbarToggle<CR>
nmap <C-n> :NERDTreeToggle<CR>
map <F1> v]}zf

set nocompatible  " be iMproved
behave mswin

syntax on " syntax highlighting
set nu " line number
set ts=4
set sw=4
set softtabstop=4
set expandtab " tab을 space로 저장
set scrolloff=15 " scroll offset. 15줄 범위에서부터 scroll
set ruler " 현재 row, col을 출력
set autoindent
set cindent
set incsearch " incremental search
set hlsearch " 검색 결과 강조
set ignorecase " 대소문자 무시 검색
set smartcase " 대문자가 검색 문자열에 있을때는 noignorecase
set laststatus=2 " vim-powerline이 꾸며주는 상태바를 항상 출력하기 위해
set hidden

" sound, visual bell 둘 다 비활성화.
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" windows gvim에서 utf8로 인코딩 설정시 메시지가 깨져서 영문 메시지를 사용
set enc=utf-8
set fencs=ucs-bom,utf-8,cp949
set fenc=utf-8
if has("win32")
	lang mes en

		" E303: Unable to open swap file for [No Name], recovery impossible
		" 방지하기 위해서 swap 파일을 저장할 디렉토리를 지정해 준다.
		" mac에서는 문제가 없으므로 win32에서만
		set directory=.,$TEMP
endif

if has('gui_running')
	set guioptions-=T " no toolbar
		set guioptions-=m " no memnubar
	" windows gvim에서 encoding을 utf-8로 설정하면 메뉴가 깨져서 langmenu를
	" 설정해 준다. 좀 무식해 보여...
	if has("win32")
		source $VIMRUNTIME/delmenu.vim
		set langmenu=ko_kr.utf-8
		source $VIMRUNTIME/menu.vim
	endif
endif

" Changing background color in vim at a certain column - stackoverflow
" set cc=80
" highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

" ctrl-j 로 라인을 분리.
" http://goo.gl/qxOlY
nnoremap <NL> i<CR><ESC>

autocmd BufWinEnter *.{md,mkd,mkdn,mark*} silent setf markdown

" ctrlp ignore
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
		\ 'dir':  '\v[\/]\.(git|hg|svn)$',
		\ 'file': '\v\.(exe|so|dll)$',
		\ 'link': 'some_bad_symbolic_links',
		\ }
